name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: svelte-check
        run: bun check
      - name: eslint
        run: bun lint
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@master
